sonata_admin:
    title: RedNose Admin
    security:
        handler: sonata.admin.security.handler.role
    templates:
#        layout:  RednoseFrameworkBundle:Admin:standard_layout.html.twig
        user_block:  RednoseFrameworkBundle:Admin\Core:user_block.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
