_libbit_framework_login:
    pattern: /login
    defaults: { _controller: LibbitFrameworkBundle:Security:index }

_libbit_framework_login_check:
    pattern: /login_check

_libbit_framework_logout:
    pattern: /logout
    defaults: { _controller: LibbitFrameworkBundle:Security:logout }

