language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script: 
  - echo "memory_limit=3G" > travis.php.ini 
  - phpenv config-add travis.php.ini
  - composer install --dev --prefer-source
