language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - echo "memory_limit=3G" > travis.php.ini
  - phpenv config-add travis.php.ini
  - composer install --prefer-source
  - composer dump-autoload

script:
  - phpunit -c phpunit.xml.dist
