rednose_framework:
    resource: "@RednoseFrameworkBundle/Controller/"
    type:     annotation
    prefix:   /

device:
    resource: "@RednoseFrameworkBundle/Resources/config/routing/device.xml"

file:
    resource: "@RednoseFrameworkBundle/Resources/config/routing/file.yml"
