rednose_framework:
    resource: "@RednoseFrameworkBundle/Controller/"
    type:     annotation
    prefix:   /

rednose_framework_file:
    resource: "@RednoseFrameworkBundle/Resources/config/routing/file.yml"
