rednose_framework_core:
    resource: "@RednoseFrameworkBundle/Resources/config/routing/framework.yml"

rednose_framework_security:
    resource: "@RednoseFrameworkBundle/Resources/config/routing/security.xml"

rednose_framework_file:
    resource: "@RednoseFrameworkBundle/Resources/config/routing/file.yml"
